### PR TITLE
Update site design

### PR DESCRIPTION
**Pull request by andrewmile**
This PR updates the entire frontend with a new design.  The landing page is styled after our redesigned landing page file minus the signup form.  All other pages are styled after a previous design with modifications made to more closely match the theme of the landing page.

The following updates have been made in the process:
- Bootstrap has been removed in favor of Tailwind
- Glyphicons have been replaced with SVGs
- The `Form` facade has been removed in favor of Laravel 7 Blade components
- Added a `featured` column to the `users` table to feature speakers on the landing page
- Added a `featured` column to the `conferences` table to feature conferences on the landing page
- The unused `AuthorsController` has been removed

## Screenshots

<details>
    <summary>Landing page</summary>

### Desktop
image

### Mobile
image

</details>

<details>
    <summary>Guest pages</summary>

### How it works
image

### Speaker list
image

### Public speaker profile
image

### Public speaker profile mobile
image

### Public speaker talk
image

### Public speaker bio
image

### Public conference list
image

### Public conference list without matching filters
image

### Mobile conference list
image

### Public conference show page
image

### Nav open
image

### Mobile nav open
image

### Login
image

</details>

<details>
    <summary>Auth pages</summary>

### Dashboard
image

### Bios list
image

### Bios list mobile
image

### Edit bio
image

### Conferences list
image

### Conferences list mobile
image

### Calendar
image

### Talks list
image

### User menu
image

### Account details
image

### Edit account
image

### Delete account
image

### oAuth settings
image

</details>

## Deployment
- `composer install`
- `php artisan migrate`
- `npm install`
- `npm run production`

## Future improvements
- The calendar and oAuth settings pages have had few changes outside of colors
- The `My Talks` section of the authenticated user's conference show page has not had any changes other than colors and spacing
- The flash messages still use bootstrap styles placed inside of `app.scss`

### CODE REVIEW

**Comment by mattstauffer** [comment]
Goodness. This PR is:

- Welcome
- Exhaustive
- WELL-described! What a fantastic body of a PR description
- SCREEN-SHOTTED!

Just look at this!!

> Bootstrap has been removed in favor of Tailwind
YESSS THANK YOU JESUS

> Glyphicons have been replaced with SVGs
Oh yahhhhh

> The Form facade has been removed in favor of Laravel 7 Blade components
Oooo I haven't had much chance to play with components. Can't wait to read it.

> Added a featured column to the users table to feature speakers on the landing page
CLEVER!

> Added a featured column to the conferences table to feature conferences on the landing page
CLEVER!

> The unused AuthorsController has been removed
👌🏻


I'm going to work through the design and make some notes *that I think we can save for a later PR.*

Then I'll review the code.

**Comment by mattstauffer** [comment]
Design notes *for a later PR update*, not to hold up this PR:

image

I think we can update the style of these a bit. Different line height, maybe a different type treatment on the metadata.

image

I think this can be "CFPs"

image

I think this body text background color should be something other than the normal background color.

image

I think it'd be nice to get an actual layout here, maybe a right float and/or some kind of special treatment 

image

I think we should use a different color here than this blue bg


But this is so good. Again, don't worry about these items now. off to the code review!

**Comment by andrewmile** [comment]
Hey Matt, thank you for your kind words about the PR :) I went ahead and made the `CFP's` -> `CFPs` change and I'll note the other design changes you mentioned for a future PR.

**Review by mattstauffer — CHANGES_REQUESTED** [review]
Submitting my partial review so, in case Keith reviews instead of me, he can have access to it

**Comment by mattstauffer** [comment]
Thanks so much for your amazing hard work on this!!

**Pull request merged**
